repos:
  # clear output cells in juypter notebooks
  - repo: local
    hooks:

      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace

      - id: check-copyright
        name: check-copyright
        files: .*
        stages: [pre-commit]
        language: script
        entry: /bin/bash scripts/check-copyright.sh

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
